[package]
name = "sudoku-ffi"
version = "0.2.0"
authors = ["Emerentius <emerentius@arcor.de>"]
readme = "README.md"
license = "MIT/Apache2"

[dependencies]
libc = "0.2.41"

[dependencies.sudoku]
version = "0.6.2"
git = "https://github.com/emerentius/sudoku"
rev = "1386e037c73a643763612dcdc9b4736b82624954"
#branch = "strategy_solver"

[lib]
crate-type = ["cdylib", "staticlib"]
