[package]
name = "sudoku-ffi"
version = "0.2.0"
authors = ["Emerentius <emerentius@arcor.de>"]
readme = "README.md"
license = "MIT/Apache2"

[dependencies]
sudoku = "0.6.2"
libc = "0.2.41"

[lib]
crate-type = ["cdylib"]
