[package]
name = "sudoku-ffi"
version = "0.2.0"
authors = ["Emerentius <emerentius@arcor.de>"]
readme = "README.md"
license = "MIT/Apache2"

[dependencies]
libc = "0.2.41"

[dependencies.sudoku]
version = "0.6.2"
git = "https://github.com/emerentius/sudoku"
rev = "ad64ff47984c0cc2d4e014373809fa17d138e7cb"
#branch = "strategy_solver"

[lib]
crate-type = ["cdylib", "staticlib"]
