[package]
name = "sudoku-ffi"
version = "0.2.0"
authors = ["Emerentius <emerentius@arcor.de>"]
readme = "README.md"
license = "MIT/Apache2"

[dependencies]
libc = "0.2.41"

[dependencies.sudoku]
version = "0.6.2"
git = "https://github.com/emerentius/sudoku"
rev = "f14bcdff0fe0cc26af6df0c62bed76565687fa21"
#branch = "strategy_solver"

[lib]
crate-type = ["cdylib", "staticlib"]
